### ISSUE TITLE
Mail extention/detail don't work on fresh install

### ISSUE THREAD

**Issue by Noxeus** [progmaticltd/homebox#88] opened 2019-02-25 18:02 UTC
I just deployed a fresh VPS using these awesome playbooks, so first of all thanks for those, they worked (almost) perfectly.

What works: sending and receiving mail on both user@mail.com and useralias@mail.com, roundcube, sogo, rspamd, ufw, etc.

However, what doesn't seem to work is using the mail extention (`user+foo@mail.com` or `useralias+foo@mail.com`) option, and I can't get it to work.

The delimiter seems to be set in both postfix `main.cf`, dovecot `15-lda.conf` and `90-sieve.conf` but sending an email (from gmail) to these mailadresses results in an error:

```
Feb 25 13:37:48 homebox postfix/smtpd[10806]: connect from mail-ed1-f52.google.com[209.85.208.52]
Feb 25 13:37:48 homebox postfix/smtpd[10806]: warning: connect to Milter service inet:localhost:32000: Connection refused
Feb 25 13:37:48 homebox postfix/smtpd[10806]: Anonymous TLS connection established from mail-ed1-f52.google.com[209.85.208.52]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Feb 25 13:37:48 homebox postfix/smtpd[10806]: NOQUEUE: reject: RCPT from mail-ed1-f52.google.com[209.85.208.52]: 554 5.7.1 <user+test@mail.com>: Recipient address rejected: Unknown user; from=<otheruser@gmail.com> to=<user+test@mail.com> proto=ESMTP helo=<mail-ed1-f52.google.com>
Feb 25 13:37:48 homebox postfix/smtpd[10806]: disconnect from mail-ed1-f52.google.com[209.85.208.52] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7
```

I searched about everywhere and it seems that the configs already has all the suggestions I can find. Maybe someone here can help?

I didn't paste my configs here, because I haven't edited them in any way, they are just how they are in the git.

**Comment by arodier** [comment] 2019-03-12 07:18
Hello Noxeus,

Thank you for the feedback and sorry for the late answer.

I have noticed this as well, recently, and I think I found the root cause. I think it is fixed in the dev branch.

I am working on a continuous integration with a VPS, to test all the features as well, hopefully, this should not happen again.

Kind regards,
André

**Comment by Noxeus** [comment] 2019-03-12 18:50
Hi arodier, thanks for the response anyhow :)
Do you have any idea where the problem is occuring? That way I can try to fix my already deployed setup!

**Comment by arodier** [comment] 2019-03-12 21:07
Hello Noxeus,

I think it is a misconfiguration of postfix and Dovecot. You can try to fix it manually, but this will take time and would risk breaking compatibility with the next stable version.

If you can wait a few days, I will merge the dev branch in the master branch, and you should be able to redeploy only postfix and dovecot.

There is no risk redeploying both servers, unless you have modified the configuration files too much.

Kind regards,
André

**Comment by Noxeus** [comment] 2019-03-12 21:08
Superb, I'll keep an eye out! 




Outlook voor Android downloaden







On Tue, Mar 12, 2019 at 10:07 PM +0100, "André Rodier" <notifications@github.com> wrote:












Hello Noxeus,



I think it is a misconfiguration of postfix and Dovecot. You can try to fix it manually, but this will take time and would risk breaking compatibility with the next stable version.



If you can wait a few days, I will merge the dev branch in the master branch, and you should be able to redeploy only postfix and dovecot.



There is no risk redeploying both servers, unless you have modified the configuration files too much.



Kind regards,


André

**Comment by arodier** [comment] 2019-03-16 20:20
Hello Noxeus,
The good news is I found the issue, or at least the main cause.
The bad news is I will probably publish the update tomorrow only.
In the meantime, if you want to test, here one way to do it:
Just disable the quota service in postfix.
It seems the quota reject the email first when it contains an extension.

Try to comment this line in postfix/main.cf:
check_policy_service inet:localhost:***

André

**Comment by Noxeus** [comment] 2019-03-16 20:34
That seems to have done something, the email wasn't rejected
Now to figure out where these 'detailed' mails end up, cause they're not in my inbox. I can it went through in the logs though.
Thanks André.

**Comment by arodier** [comment] 2019-03-17 06:22
Hello Noxeus,
Thanks for your time testing the project, this is kind.

I am reopening the bug, because I want it to be fixed in the master branch.

I am investigating the quota script.

Kind regards,
André

**Comment by arodier** [comment] 2019-03-17 21:36
OK, this is now fixed in the master branch, and I have added tests to check email aliases and extensions. You can test the master branch if you want. Come back to me if you have any issue.

**Closed by arodier** 2019-03-17 21:36 UTC
