### ISSUE TITLE
a fix, some errors and a thanks to the devs

### ISSUE THREAD

**Issue by n1ete** [progmaticltd/homebox#20] opened 2018-09-04 22:07 UTC
hey there, first i wanna thank you for this playbook... i startetd to develop my local fork a few days on it!

i have a fix suggestion:
1. 
in the clamav main task you should remove line 91-97, since u dropped the `virus-alert.sh` script. 

got also some errors:
1. 
the main install task is not be able to create the mail dirs until i create the users, i added in `system.yml`, locally on the homebox machine with `useradd -r username`
2. 
the rspamd role main task failed everytime with line 91-93 included. Is dmarc reporting also dropped?
3. 
dovecot certbot task failed because apache is listening already on port 80
i guess i could write an "stop and start part" into certificates main role for it?

**Comment by arodier** [comment] 2018-09-05 08:12
Hello,
Thanks for the feedback, I will be able to test all of this this weekend, and I will come back to you.
I was in holidays or busy in July and August, but I am planning to start again the development this month.
Kind regards,
André.

**Comment by arodier** [comment] 2018-09-11 20:53
I have fixed the first suggestion, but I need more time to test the others:

1. There should be no need to add the users manually, they are synchronised with LDAP. Perhaps something is wrong, I will test again from scratch.
2. I need to test more dmarc reporting, it is something I did not test thoroughly.
3. The certbot task is already stopping the nginx server, so something is wrong again.

**Comment by arodier** [comment] 2018-09-13 12:51
Give me the time to merge on master, and to do the whole test suite. Also, it would be better to write one issue for all the points you mentioned.

**Comment by arodier** [comment] 2018-09-30 13:17
Hello,
I have made some updates on the dev branch, that should fix all the errors above. If you have the time, to test, perfect.

- Added missing part to activate roundcube web site. 
- Fixed a typo in the role for external IP address detection
- Major DNS, certificates and documentation update
- Updated most sites for certbot webroot deployment 
- Added missing value in default dmarc settings 
- Also load default settings for external IP address detection. 
- Updated integration tests for DNS records.

Thanks.

**Comment by arodier** [comment] 2018-10-07 08:47
1. the main install task is not be able to create the mail dirs until i create the users, i added in system.yml, locally on the homebox machine with useradd -r username
Users should be created automatically, as long as they are defined in the system.yaml file. You should not create users manually, or they will not use the LDAP authentication and SSO.
Can you tell me what are the initial conditions to reproduce this bug?

2. the rspamd role main task failed everytime with line 91-93 included. Is dmarc reporting also dropped?
I could not reproduce this bug yet, at least it works for me using a standard Debian, freshly installed. Same as before, I would be interesting to know the initial conditions.

3. dovecot certbot task failed because apache is listening already on port 80
i guess i could write an "stop and start part" into certificates main role for it?
Yes, the certbot was using the "standalone" options before 10/2018. It is now using a dedicated webroot, which means you do not have to stop the nginx server to renew your certificates.

I am closing the issue, now. Please, open a new one for each bug you may find.

**Closed by arodier** 2018-10-07 08:47 UTC
